name: RadXPriceBot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: RadXPriceBot.sln
      Project_Path: RadXPriceBot.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Create Resources directory
      shell: pwsh
      run: |
        if (-not (Test-Path -Path "Resources")) {
          New-Item -ItemType Directory -Path "Resources"
        }

    - name: Add Logo Image
      shell: pwsh
      run: |
        if (-not (Test-Path -Path "Resources\RadXLogo.png")) {
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/microsoft/fluentui-system-icons/master/assets/Bot/SVG/ic_fluent_bot_24_regular.svg" -OutFile "Resources\RadXLogo.png"
        }

    - name: Build with MSBuild
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }}

    - name: Test
      shell: pwsh
      run: |
        $testProjects = Get-ChildItem -Path . -Filter "*.Tests.csproj" -Recurse
        if ($testProjects.Count -gt 0) {
          foreach ($project in $testProjects) {
            Write-Host "Running tests for: $($project.FullName)"
            dotnet test $project.FullName --configuration ${{ matrix.configuration }} --no-build --verbosity normal
          }
        } else {
          Write-Host "No test projects found."
        }

    - name: Publish with MSBuild
      run: msbuild ${{ env.Project_Path }} /t:Publish /p:Configuration=${{ matrix.configuration }} /p:PublishDir=publish\ /p:SelfContained=true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:PublishReadyToRun=true /p:PublishTrimmed=false /p:RuntimeIdentifier=win-x64

    - name: Package Application
      run: Compress-Archive -Path publish\* -DestinationPath RadXPriceBot-${{ matrix.configuration }}.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RadXPriceBot-${{ matrix.configuration }}
        path: RadXPriceBot-${{ matrix.configuration }}.zip
        if-no-files-found: error
